{% set name = "clhpp" %}
{% set version = "2022.09.30" %}
{% set sha256 = "999dec3ebf451f0f1087e5e1b9a5af91434b4d0c496d47e912863ac85ad1e6b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  always_include_files:
    - include/CL/opencl.hpp
    - include/CL/cl2.hpp

requirements:
  build:
    - cmake
    - make   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python >=3.5
  host:
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - khronos-opencl-icd-loader  # [win]
    - ocl-icd                    # [linux]

test:
  commands:
    - test -d "${PREFIX}/include/CL"                     # [unix]
    - test -f "${PREFIX}/include/CL/opencl.hpp"          # [unix]
    - test -f "${PREFIX}/include/CL/cl2.hpp"             # [unix]
    - if not exist %LIBRARY_INC%\\CL exit 1              # [win]
    - if not exist %LIBRARY_INC%\\CL\\opencl.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\\CL\\cl2.hpp exit 1     # [win]

about:
  home: https://github.com/KhronosGroup/OpenCL-CLHPP
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: OpenCL Host API C++ bindings

  dev_url: https://github.com/KhronosGroup/OpenCL-CLHPP
  doc_url: http://github.khronos.org/OpenCL-CLHPP

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - jakirkham
