{% set name = "clhpp" %}
{% set version = "2.0.13" %}
{% set sha256 = "8ff0d0cd94d728edd30c876db546bf13e370ee7863629b4b9b5e2ef8e130d23c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  always_include_files:
    - include/CL/cl2.hpp
    - include/CL/opencl.hpp

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
  host:
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - khronos-opencl-icd-loader  # [win]
    - ocl-icd                    # [linux]

test:
  commands:
    - test -d "${PREFIX}/include/CL"                     # [unix]
    - test -f "${PREFIX}/include/CL/cl2.hpp"             # [unix]
    - test -f "${PREFIX}/include/CL/opencl.hpp"          # [unix]
    - if not exist %LIBRARY_INC%\\CL exit 1              # [win]
    - if not exist %LIBRARY_INC%\\CL\\cl2.hpp exit 1     # [win]
    - if not exist %LIBRARY_INC%\\CL\\opencl.hpp exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/OpenCL-CLHPP
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: OpenCL Host API C++ bindings

  dev_url: https://github.com/KhronosGroup/OpenCL-CLHPP
  doc_url: http://github.khronos.org/OpenCL-CLHPP

extra:
  recipe-maintainers:
    - inducer
    - jakirkham
