matrix:
  - []
  - [[OSX_VARIANT, 'pocl']]

travis:
  secure:
    BINSTAR_TOKEN: LsgIbTUkqeNqKzsaaJ2s3QphqDhASPVM0IGo8vM+rHxMDE9gacakYIcCazuF/bIUz0g33uMNHbkciKLJRPbzdaVEyDAtmamm0D1l06Q7f7bev5ZeI239+wOXJ3U+AI9e/MaWN6vMjSNfTRF17M9eC1YTB0EqdiC+LikNx1DtGV6Fb8gB9YvcdwHkOceUF+KdtMxuCm+Fjde3lb2seSlDfqRB5nB9wCHEDBNHJmHAR5yEyYY2t9auY8EdUgnSos8bAqwvNp5Q0cHFBVMjRsZ6w2+/xEZEuS0LqJgjKu0TDN8GKdYLUXBgcBiYG2Xzu/SvOKuAYG0aDMUOEsf+oVGrbJXyHivhBUZg2KeaZ+ikqgMkRyAmtL8pkRz6w1zP30GeWHIc2nA8y+BsntU7bJlw84d/6EQC1FrXnckemXOwmiMZli3nV5PXpulIoGTu93qOUKHSSC1BWVULE1CbfKDRmYFI2BT29AKFE98Ax/kgBYXTFKWVF260uJnx79enIaU9ZBij4+urzQtuPcE4zxW41FopWfcbIluDQbJtR2SIVGkc+neH1bgJ5ZK/Ca3YLZ0IZMHIet2bpH7I4i/bAtpg7+ccAYMmAXhdGoP2d6Re2rZip0fR7LNRufsK9P0rZUuKXGvd/VcQwyzFu/92JIyE9mfDII9+9h8dEes4KRb//EU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
