travis:
  secure:
    BINSTAR_TOKEN: ySYSnpUd8w2vv1ln7MSey9/te6yeH4suJkaUwi8TEY/6Arji2/dSLqxpQ5tU4/u/vonw0+uEyGxQYn7toI4ebMZNTpUOCUEQovMPfhbqM4u/y8fGYNv0TLS8IarI4+x2YzBtlWI0fM9TsySPMX7ZHJcRbn70gDs816UhM/rNmqd4VSLSQETs57ukqJHiPtRm1j90k6JE5Wn51v9E3UiUiFrohRORZN6POiJxUBa1s7wJnsz/XRj7Y4lfUQoC4XDmx3qQwU8Sxyk1NJ5NJxXEyKQDGAe56wAkWaLbwDCQYSMwbRvTW70AZKL/wLbtTSk6gtaPelQhMmlPyKTxGVBicpt6WQ8Cefz2X+zKWobyoBEK5lVh746OoOHF3gZrhdLCrNMCCYgHtTnlIqKmHR3pLvNqYUZHj8Obfa7HtR3C9uPESngsiMlXWk722I73tXMSngtiVqtIUcU4kEVso7plQ1WjqW/rLUeT8iAFWaeXq8Z1UAPbIbn6VATGh2rdPXI39vSgtFA6mKJbYboMGtBLfx+hrYVQS4/tBjYo+L6RqCseK/HAPG9+Aqu33XXGWziEddUl5m76KhasJsJxdrOyaNJYJZQjikRHrjTcbFgVXZlxhHqkFlG0YP+ht4RXZQLL3E/TSSTxWLzaPqlUMotZ9P8dFaSmF65cO15oTtnUXmk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
